### PR TITLE
docs: recommend using Rspack instead of webpack SWC

### PR DESCRIPTION
**Pull request by chenjiahan**
## Summary

Recommend using Rspack instead of the webpack SWC plugin.

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by zllkjc** [comment]
I have another WIP PR about plugin documentation, which will create a new menu `Plugin` like Rsbuild. Maybe we can not merge this first, and I can handle it together~

**Comment by zllkjc** [comment]
Nice. I have another WIP PR https://github.com/web-infra-dev/modern.js/pull/6199 about plugin docs, which add new menu for Plugin like Rsbuild.

Do this PR need to merge before rsbuild 1.0 release ? Otherwise i can add these change to my pr, avoid conflict, which maybe merge before 09.12

**Comment by chenjiahan** [comment]
There is no rush to merge this PR, take your time 😄

**Review by 9aoy — APPROVED** [review]

**Comment by zllkjc** [comment]
#6199 @chenjiahan @9aoy cc~

**Pull request closed without merging**
