### PR TITLE
feat(devtools): new page `current storage`

### PR DESCRIPTION
**Pull request by Asuka109**
## Summary

https://github.com/web-infra-dev/modern.js/assets/18379948/130c3ddd-0d43-4cbf-a87d-a3dadb8a2bb8

- Generate identifier for presets automatically.
- Extract unified card component (for internal usages).
- Add new page to inspecting current storage status.
- Fix loading spinner position issue.

Pending by https://github.com/web-infra-dev/modern.js/pull/5729 & https://github.com/web-infra-dev/modern.js/pull/5733.

## Checklist

- [ ] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by zllkjc** [comment]
I wonder how to find the current storage. is there any tag in the presets ?

**Comment by zllkjc** [comment]
The Flame label is not easy to understand as apply. Is this a ui reference. Consider adding text and icons together in "fire" ?

**Comment by Asuka109** [comment]
> I wonder how to find the current storage. is there any tag in the presets ?

I perfer to highlight the applied presets by their key-values. In other words a preset will be highlighted since its records matches current storage status even if it doesn't applied. I am planning to feature it in next pull request.

**Comment by Asuka109** [comment]
> Sure, we already have a tooltip here, but I am considering reducing the delay of the initial display as it is not significant. Maybe in the next pr as well?

**Review by zllkjc — APPROVED** [review]

**Pull request merged**
