### PR TITLE
chore: use pnpm@8.9 in corepack

### PR DESCRIPTION
**Pull request by bvanjoi**
This PR brings:

- Ensure to use `﻿pnpm@>=8.7` to adopt the highest resolution by default.
- Experiment with `﻿pnpm@8.9` in CI to evaluate if it can reduce the linking time by CoW during installation.

### CODE REVIEW

**Comment by bvanjoi** [comment]
No significant time savings were found.

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
👍🏻👍🏻

**Comment by chenjiahan** [comment]
> No significant time savings were found.

The macOS CI seems faster.

before:

- 2m 28s https://github.com/web-infra-dev/modern.js/actions/runs/6478733373/job/17590991464
- 2m 33s https://github.com/web-infra-dev/modern.js/actions/runs/6466689446/job/17555223573

after:

- 1m 38s https://github.com/web-infra-dev/modern.js/actions/runs/6481309345/job/17598550151

**Comment by chenjiahan** [comment]
Not sure if it’s caused by network differences..

**Comment by bvanjoi** [comment]
I propose that we can create a PR for ﻿pnpm to display the time spent on the resolution and linking steps.

**Comment by chenjiahan** [comment]
LGTM~

**Pull request merged**
