### PR TITLE
Fix/unsafe replace

### PR DESCRIPTION
**Pull request by GiveMe-A-Name**
## Summary

The unsafeReplace may can't find search string,
We should handle this.

## Checklist

- [ ] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by GiveMe-A-Name** [comment]
!canary

**Comment by GiveMe-A-Name** [comment]
!canary

**Comment by GiveMe-A-Name** [comment]
!canary

**Comment by GiveMe-A-Name** [comment]
!canary

**Comment by GiveMe-A-Name** [comment]
!canary

**Review by yimingjfe — APPROVED** [review]

**Pull request merged**
