### PR TITLE
feat: support split-by-module with rspack

### LINKED ISSUE #5054: [Feature]: support `split-by-module` chunk split strategy when use rspack
### What problem does this feature solve?

Added in rspack 0.4.1 is support function type for `splitChunks.{cacheGroup}.{test, name}`. So we can support `split-by-module` chunk split strategy in modern.js when use rspack.

More details can be found in the: https://github.com/web-infra-dev/rspack/releases/tag/v0.4.1

### What does the proposed API look like?

```js
performance: {
  chunkSplit: {
    strategy: 'split-by-module',
  },
},
```

### PR DESCRIPTION
**Pull request by SyMind**
## Summary

Support split-by-module chunk split strategy when use rspack.

## Related Links

fix #5054 

## Checklist

- [ ] I have added changeset via `pnpm run change`.
- [x] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by SyMind** [comment]
The `module.context` in rspack is currently returning undefined. We can track the status of this issue on: [Issue #4953](https://github.com/web-infra-dev/rspack/issues/4953).

**Comment by SyMind** [comment]
Fix `Error: ENAMETOOLONG: name too long` when use rspack. Track the status of this issue on: https://github.com/web-infra-dev/rspack/pull/4964.

**Comment by SyMind** [comment]
@chenjiahan With the release of repack [v0.4.3](https://github.com/web-infra-dev/rspack/releases/tag/v0.4.3), we can now support `split-by-module` when using rspack.

**Comment by chenjiahan** [comment]
@SyMind Good news 😄, so can we merge this PR now?

**Comment by SyMind** [comment]
@chenjiahan Yes, I think it's ok.

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
Thanks for your contribution!

Can you submit a Pull Request to the Rsbuild repo too? Rsbuild is the new version of Modern.js Builder.

https://github.com/web-infra-dev/rsbuild

**Pull request merged**
